project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Land Cover to Satellite Image Translation with Pix2Pix GAN Model"
  page-footer:
    left: "majiayue@design.upenn.edu"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/project-icon.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Jiayue-Ma
        text: "Personal Github Profile"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: Land Cover to Satellite Image Translation Project/index.qmd
        contents:
          - Land Cover to Satellite Image Translation Project/1-1.ipynb
          - Land Cover to Satellite Image Translation Project/1-2.ipynb
          - Land Cover to Satellite Image Translation Project/1-3.ipynb
          - Land Cover to Satellite Image Translation Project/1-4.ipynb
      - section: Land Cover to Satellite Image Translation Project/2-1.ipynb
        contents: Land Cover to Satellite Image Translation Project/2-1.ipynb
      - section: Land Cover to Satellite Image Translation Project/3-1.ipynb
        contents: Land Cover to Satellite Image Translation Project/3-1.ipynb
      - section: Land Cover to Satellite Image Translation Project/4-1.ipynb
        contents: Land Cover to Satellite Image Translation Project/4-1.ipynb
      - section: Land Cover to Satellite Image Translation Project/5-1.ipynb
        contents: Land Cover to Satellite Image Translation Project/5-1.ipynb
      - section: Land Cover to Satellite Image Translation Project/6-1.ipynb
        contents: Land Cover to Satellite Image Translation Project/6-1.ipynb
      - about.qmd

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
